### ISSUE TITLE
[Patch] Browse through images in directory after opening a single file

### ISSUE THREAD

**Issue by polirritmico** [nsxiv/nsxiv-extra#11]
Hi, I just want to share this code adaptation I made from the [qsmodo sxiv fork](https://github.com/qsmodo/sxiv). A patch to browse through the images in the directory after opening a single file. I strongly prefer this patch over nsxiv-rifle and maybe it could be useful to others.

https://gist.github.com/polirritmico/63a1ad755f6b0eb1af57388c80957174

Regards

**Comment by N-R-K** [comment]
One problem I had with that patch is that it's noticeably slow compared to nsxiv-rifle (run via dash) when opening bigger directories. See [this post](https://github.com/bakkeby/sxiv-flexipatch/issues/8#issuecomment-1065843492) for a more detailed explanation.
