### ISSUE TITLE
command in key-handler not working

### ISSUE THREAD

**Issue by yogeshdcool** [nsxiv/nsxiv-extra#13]
os:arch
I have this in the key-handler file in .config/nsxiv/exec/
```
case "$1" in
"C-b")      wal -i "$file";;
esac
```
but when I use C-x C-b it's not working Im getting this in my terminal
```
wal: error: No input specified.
--backend, --theme, -i or -R are required.
```

**Comment by N-R-K** [comment]
nsxiv doesn't set any `$file` variable. The filenames are passed to the keyhandler via stdin. You need to extract the filename from there. Try the following:

```sh
read -r file; wal -i "$file";;
```

Also see the example key-handler for more examples: https://github.com/nsxiv/nsxiv/blob/master/examples/key-handler

**Comment by yogeshdcool** [comment]
> nsxiv doesn't set any `$file` variable. The filenames are passed to the keyhandler via stdin. You need to extract the filename from there. Try the following:
> 
> ```shell
> read -r file; wal -i "$file";;
> ```
> 
> Also see the example key-handler for more examples: https://github.com/nsxiv/nsxiv/blob/master/examples/key-handler

Thank you it worked
