### ISSUE TITLE
make nsxiv-thumb more POSIX

### ISSUE THREAD

**Issue by pfr-dev** [nsxiv/nsxiv-extra#16]
Is it possible to make the nsxiv-thumb script more POSIX compliant? I'd love to use this on my BSD machine.

**Comment by XPhyro** [comment]
The non-POSIXness comes from two aspects:
- Handling *all* file paths (including those with `\n`, `\r` and all sorts of other absurd characters)
- Performance increase (thanks to `-{min,max}depth`)

If you would be willing to give these up, the only non-POSIX dependency would be `ffmpegthumbnailer`. I could write a POSIX alternative if this sounds satisfactory.

**Comment by pfr-dev** [comment]
Hey @XPhyro thanks for the reply. I suppose some functionality is always better than none right!? I'd love for a POSIX version of this script. `ffmpegthumbnailer` is available in the NetBSD repositories so I have that installed. It's only the `sort` and `sed` errors that need attention. 

I managed to work around the `find` error relating to the `-printf` flag by replacing `-printf "%P\0"` with `-print0`. Not sure what kind of unforeseen effects this will have though. 

The errors I get now look like this:

```
~/Videos $ ./nsxiv-thumb.sh
sort: unknown option -- z
usage: sort [-bdfHilmnrSsu] [-k kstart[,kend]] [-o output] [-R char] [-T dir]
             [-t char] [file ...]
   or: sort -C|-c [-bdfilnru] [-k kstart[,kend]] [-o output] [-R char]
             [-t char] [file]
xargs: sh terminated by SIGPIPE
xargs: (null) terminated by SIGPIPE
sed: unknown option -- z
Usage:  sed [-aElnru] command [file ...]
        sed [-aElnru] [-e command] [-f command_file] [-I[extension]]
            [-i[extension]] [file ...]
nsxiv: No valid image file given, aborting
```

**Comment by XPhyro** [comment]
Feel free to re-open the issue if this does not work. Also, this repository might get archived soon. You would be able to continue the discussion on https://codeberg.org/nsxiv/nsxiv-extra/issues/16.
