### ISSUE TITLE
[nsxiv-extra patch] Video thumbnails?

### ISSUE THREAD

**Issue by owbosh** [nsxiv/nsxiv-extra#4]
I know nsxiv is meant to be an image viewer, but the ability to thumbnail video files is the one feature GUI file managers have that prevent me from ditching them altogether. I just can't find a simple, scriptable program that can do this. The program doesn't even have to actually play the videos, just list some thumbnails that open up your preferred video player when selected.

So this is could both be a nsxiv-extra patch request (if someone who knows more than me is kind enough to work on it) or a request for some guidance on how I could start working on it. I know a bit of C but it's hard to wrap my head around the source code. Any help would be much appreciated, thank you.

**Comment by N-R-K** [comment]
@Naheel-Azawy Just a small observation: this would lead to out of bound access if the `file` happens to be less than 4 chars.
https://github.com/Naheel-Azawy/sxiv/blob/3824e508e461eb42ce467542fec513f0b2c6d315/video.c#L10

Also maybe look into libmagic for detecting filetype instead of extension check.

**Comment by TAAPArthur** [comment]
@owbosh I like the idea and threw together support for [my image viewer](https://github.com/TAAPArthur/libimageloader/blob/ffmpeg_loader/ffmpeg_loader.h). Basically the same as the others, but uses a different ffmpeg command: `ffmpeg -i - -vframes 1 -f image2 - >$OUTPUT <$INPUT`. In the example, the first frame of the video is extracted to to memory and passed to a decoder (like libpng or imglib2).

**Comment by N-R-K** [comment]
I haven't tried it, but if `nsxiv-thumb` works then shouldn't we close this? @XPhyro

**Comment by XPhyro** [comment]
> I haven't tried it, but if `nsxiv-thumb` works then shouldn't we close this? @XPhyro

From what I understand, @owbosh requests a native patch. If `nsxiv-thumb` suffices for them we can close this issue.

**Comment by Naheel-Azawy** [comment]
> @Naheel-Azawy Just a small observation: this would lead to out of bound access if the `file` happens to be less than 4 chars. https://github.com/Naheel-Azawy/sxiv/blob/3824e508e461eb42ce467542fec513f0b2c6d315/video.c#L10
> 
> Also maybe look into libmagic for detecting filetype instead of extension check.

Thanks @N-R-K for the observation. I have seen libmagic when I first wrote this but I was lazier than to use it. Anyway, check my last commit, now it uses libmagic.
Checking the mimetype is still slower than simple string comparison. So I kept libmagic check as a fallback.
I'll probably update the repo soon with some fixes/cleanups as well.
I'm writing this while working on tons of other stuff. So let me know if you find anything wrong.

**Comment by owbosh** [comment]
@XPhyro I'm currently using @Naheel-Azawy's code for video thumbs in nsxiv (thank you for your work btw), which is working pretty well for me.
