### ISSUE TITLE
Patch For Square Thumbnails (Request)

### ISSUE THREAD

**Issue by Amarakon55** [nsxiv/nsxiv-extra#8]
By default, nsxiv maintains the aspect ratio of each image when viewing them. I would like for a patch that forces all of the images being viewed to be square and to take up the entire window. Here is an existing patch for sxiv that didn't work for nsxiv:
https://github.com/explosion-mental/sxiv/blob/main/patches/square-thumbs.patch

**Comment by explosion-mental** [comment]
yeah why not

**Comment by explosion-mental** [comment]
https://github.com/explosion-mental/sxiv/blob/main/patches/nsxiv-square-thumbs-20220206-5807871.diff

**Comment by explosion-mental** [comment]
would appreciate if you could pr this

**Comment by Amarakon55** [comment]
Thank you, it looks great and it works. I don't know what pr means.
Although it has one issue; there is still unnecessary space at the left and right sides.

**Comment by N-R-K** [comment]
> would appreciate if you could pr this

You should be able to push to this repo directly.

**Comment by Amarakon55** [comment]
I cloned the source code and added the patch and commited it. I tried to push with "git push" but I need to log in.

**Comment by XPhyro** [comment]
> I cloned the source code and added the patch and commited it. I tried to push with "git push" but I need to log in.

I believe N-R-K meant that explosion-mental should be able to push it, as they are a member of the nsxiv organisation.

**Comment by Amarakon55** [comment]
Oh okay.

**Comment by N-R-K** [comment]
Yes that was meant for @explosion-mental , sorry for confusion.
